### ISSUE TITLE
Python Script Throwing Errors

### ISSUE THREAD

**Issue by hardikjain1** [WangYihang/UsbMiceDataHacker#7]
```Traceback (most recent call last):
  File "/home/kali/USB-Mouse-Pcap-Visualizer/usb-mouse-pcap-visualizer.py", line 112, in <module>
    main()
  File "/home/kali/USB-Mouse-Pcap-Visualizer/usb-mouse-pcap-visualizer.py", line 107, in main
    plt.scatter(xs, ys, c=colors, alpha=alphas)
  File "/home/kali/.cache/pypoetry/virtualenvs/usb-mouse-pcap-visualizer-tIDkKrMK-py3.11/lib/python3.11/site-packages/matplotlib/pyplot.py", line 2862, in scatter
    __ret = gca().scatter(
            ^^^^^^^^^^^^^^
  File "/home/kali/.cache/pypoetry/virtualenvs/usb-mouse-pcap-visualizer-tIDkKrMK-py3.11/lib/python3.11/site-packages/matplotlib/__init__.py", line 1446, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.cache/pypoetry/virtualenvs/usb-mouse-pcap-visualizer-tIDkKrMK-py3.11/lib/python3.11/site-packages/matplotlib/axes/_axes.py", line 4667, in scatter
    collection = mcoll.PathCollection(
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.cache/pypoetry/virtualenvs/usb-mouse-pcap-visualizer-tIDkKrMK-py3.11/lib/python3.11/site-packages/matplotlib/collections.py", line 994, in __init__
    super().__init__(**kwargs)
  File "/home/kali/.cache/pypoetry/virtualenvs/usb-mouse-pcap-visualizer-tIDkKrMK-py3.11/lib/python3.11/site-packages/matplotlib/_api/deprecation.py", line 454, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.cache/pypoetry/virtualenvs/usb-mouse-pcap-visualizer-tIDkKrMK-py3.11/lib/python3.11/site-packages/matplotlib/collections.py", line 201, in __init__
    self._internal_update(kwargs)
  File "/home/kali/.cache/pypoetry/virtualenvs/usb-mouse-pcap-visualizer-tIDkKrMK-py3.11/lib/python3.11/site-packages/matplotlib/artist.py", line 1223, in _internal_update
    return self._update_props(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.cache/pypoetry/virtualenvs/usb-mouse-pcap-visualizer-tIDkKrMK-py3.11/lib/python3.11/site-packages/matplotlib/artist.py", line 1199, in _update_props
    ret.append(func(v))
               ^^^^^^^
  File "/home/kali/.cache/pypoetry/virtualenvs/usb-mouse-pcap-visualizer-tIDkKrMK-py3.11/lib/python3.11/site-packages/matplotlib/collections.py", line 815, in set_alpha
    artist.Artist._set_alpha_for_array(self, alpha)
  File "/home/kali/.cache/pypoetry/virtualenvs/usb-mouse-pcap-visualizer-tIDkKrMK-py3.11/lib/python3.11/site-packages/matplotlib/artist.py", line 1041, in _set_alpha_for_array
    if not (0 <= alpha.min() and alpha.max() <= 1):
                 ^^^^^^^^^^^
  File "/home/kali/.cache/pypoetry/virtualenvs/usb-mouse-pcap-visualizer-tIDkKrMK-py3.11/lib/python3.11/site-packages/numpy/core/_methods.py", line 45, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial, where)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: zero-size array to reduction operation minimum which has no identity
```

This is the error that shows

**Comment by WangYihang** [comment]
Thanks for reporting, do you mind to provide the pcap file?

**Comment by hardikjain1** [comment]
Here's the pcapng file, it was from a CTF competition. 
https://drive.google.com/file/d/1KWAPwRp042DLxyU56hPHLsfAxxe8NLHP/view?usp=sharing

Please acknowledge once you see this comment.

**Comment by WangYihang** [comment]
Thank you so much for providing the pcap file, I am working on it. @hardikjain1

**Comment by WangYihang** [comment]
See [usb-mouse-pcap-visualizer.py:L50-R71](https://github.com/WangYihang/USB-Mouse-Pcap-Visualizer/commit/b37f7a363dc019a9e8b18fb0ec1747cb06025e78#diff-f329143993dfe7d8bdcbc356547ee15296e5a080536eb739f1bae81e77a375a0L50-R71) for detailed changes.

**Comment by WangYihang** [comment]
New command line arguments:

![image](https://github.com/WangYihang/USB-Mouse-Pcap-Visualizer/assets/16917636/055c05dd-aa5b-4cd6-a522-2d9aa9de1ef4)

New visualizer:

![Animation](https://github.com/WangYihang/USB-Mouse-Pcap-Visualizer/assets/16917636/83f84903-b5fa-4218-b03e-05c9643a7464)

**Comment by WangYihang** [comment]
Check this [website](https://usb-mouse-pcap-visualizer.vercel.app/) for online visualizer.

![image](https://github.com/WangYihang/USB-Mouse-Pcap-Visualizer/assets/16917636/911c87c7-e551-4643-94c0-e8658a0db772)

![image](https://github.com/WangYihang/USB-Mouse-Pcap-Visualizer/assets/16917636/2b0df950-a11c-42ea-ab8c-79b41f036a8f)

**Comment by hardikjain1** [comment]
Thank you, this works now
